name: "chat-adviser-bot"

services:
  cache:
    command: --requirepass ${REDIS_PASSWORD}
    image: redis:7.2.4-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      interval: 5s
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT:-5432}:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    environment:
      LOKI_PORT: ${LOKI_PORT:-3100}
    image: grafana/grafana:10.4.0
    ports:
      - ${GRAFANA_PORT:-3200}:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - grafanadata:/var/lib/grafana

  loki:
    image: grafana/loki:3.0.0
    ports:
      - ${LOKI_PORT:-3100}:3100
    volumes:
      - lokidata:/loki

volumes:
  grafanadata:
  lokidata:
  pgdata:
  redisdata:
