name: "chat-adviser-bot"

services:
  app:
    build: .
    depends_on:
      - cache
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOKI_URL: ${LOKI_URL}
      REDIS_HOST: ${REDIS_HOST:-cache}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_WEBHOOK_DOMAIN: ${TELEGRAM_WEBHOOK_DOMAIN}
      TELEGRAM_WEBHOOK_PATH: ${TELEGRAM_WEBHOOK_PATH}
      TELEGRAM_WEBHOOK_PORT: ${TELEGRAM_WEBHOOK_PORT}
      TELEGRAM_WEBHOOK_SECRET_TOKEN: ${TELEGRAM_WEBHOOK_SECRET_TOKEN}
    restart: unless-stopped
    volumes:
      - grafanaprovisioning:/etc/grafana/provisioning

  cache:
    command: --requirepass ${REDIS_PASSWORD}
    image: redis:7.4.0-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      interval: 15s
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
    image: postgres:16.4-alpine
    ports:
      - ${DATABASE_PORT:-5432}:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    depends_on:
      - app
      - loki
    environment:
      LOKI_PORT: ${LOKI_PORT:-3100}
    image: grafana/grafana:11.1.2
    ports:
      - ${GRAFANA_PORT:-3200}:3000
    restart: unless-stopped
    volumes:
      - grafanadata:/var/lib/grafana
      - grafanaprovisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:3.1.1
    ports:
      - ${LOKI_PORT:-3100}:3100
    restart: unless-stopped
    volumes:
      - lokidata:/loki

volumes:
  grafanadata:
  grafanaprovisioning:
  lokidata:
  pgdata:
  redisdata:
