name: "chat-adviser-bot"

services:
  app:
    build: .
    depends_on:
      - cache
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST:-cache}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      WEBHOOK_DOMAIN: ${WEBHOOK_DOMAIN}
      WEBHOOK_PATH: ${WEBHOOK_PATH}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
      WEBHOOK_SECRET_TOKEN: ${WEBHOOK_SECRET_TOKEN}
    restart: unless-stopped

  cache:
    command: --requirepass ${REDIS_PASSWORD}
    image: redis:7.2.4-alpine
    ports:
      - ${REDIS_PORT:-}:6379
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      interval: 1m
      start_interval: 1s
      start_period: 15s
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT:-}:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redisdata:
