name: "chat-adviser-bot-test"

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      interval: 5s
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
    image: postgres:16.1-alpine
    ports:
      - ${DATABASE_PORT:-}:5432
