name: "chat-adviser-bot"

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    healthcheck:
      interval: 1m
      start_interval: 1s
      start_period: 15s
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT:-}:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
