{
 "title": "Main",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Level",
    "query": "Error : error, Info : info, Warn : warn"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Pulse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"bot\", level=~\"$level\"} [5m]))"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"bot\", level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "New Chats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"bot\"} |= `The bot was added to` [$__auto]))"
    }
   ]
  },
  {
   "title": "Kicked From Chats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"bot\"} |= `The bot was kicked from` [$__auto]))"
    }
   ]
  },
  {
   "title": "Profanity Found",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"bot\"} |= `A profanity was found in` [$__auto]))"
    }
   ]
  }
 ]
}