{
 "title": "Main",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Log Pulse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"bot\", level=~\"$level\"} [5m]))"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"bot\", level=~\"$level\"}"
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "New Chats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `The bot was added to` [$__auto]))"
    }
   ]
  },
  {
   "title": "Removed Chats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `The bot was kicked from` [$__auto]))"
    }
   ]
  },
  {
   "title": "Filtered Channel Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `Message on behalf of a channel was deleted` [$__auto]))"
    }
   ]
  },
  {
   "title": "Profanity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `A profanity was found` [$__auto]))"
    }
   ]
  },
  {
   "title": "Removed Bots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `A bot was removed from the chat` [$__auto]))"
    }
   ]
  },
  {
   "title": "Votebans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `Voteban started` [$__auto]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `A warning was issued` [$__auto]))"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"bot\"} |= `Update processing completed` [$__auto]))"
    }
   ]
  },
  {
   "title": "95th Percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {service_name=\"bot\"} |= `Update processing completed` | unwrap request_time [$__auto]) by (service_name)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by(service_name) (max_over_time({service_name=\"bot\"} |= `Update processing completed` | unwrap request_time [$__auto]))",
     "legendFormat": "Max latency"
    }
   ]
  }
 ]
}