# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: CI/CD

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22.11.0
      - name: Install dependencies
        run: npm ci
      - name: Build sources
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            Dockerfile
            compose.build.yml
            dist
            grafana
            package-lock.json
            package.json
            prisma

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22.11.0
      - name: Install dependencies
        run: npm ci
      - name: Run unit and integration tests
        run: npm run test:cov
      - name: Run e2e tests
        run: npm run test:e2e:cov
      - name: Run load tests
        run: npm run k6
      - name: Merge unit, integration and e2e test coverage
        run: npm run merge:cov
      - name: Check test coverage badges silently
        run: npm run make:badges -- --ci
    timeout-minutes: 15

  deploy:
    environment: |-
      ${{
        github.ref_name == 'main' && 'production'
      }}
    if: github.ref_name == 'main'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Start the app in docker
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          # Should be in the following format: ssh://[server_username]@[server_ip]:[server_ssh_port]
          # Example: ssh://root@1.1.1.1:22
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}
          LOKI_PORT: ${{ secrets.LOKI_PORT }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          # Get this variable via command: ssh-keyscan -p [server_ssh_port] [server_ip]
          # Example: ssh-keyscan -p 22 1.1.1.1
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TG_CLIENT_API_HASH: ${{ secrets.TG_CLIENT_API_HASH }}
          TG_CLIENT_API_ID: ${{ secrets.TG_CLIENT_API_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_WEBHOOK_DOMAIN: ${{ secrets.TG_WEBHOOK_DOMAIN }}
          TG_WEBHOOK_PATH: ${{ secrets.TG_WEBHOOK_PATH }}
          TG_WEBHOOK_PORT: ${{ secrets.TG_WEBHOOK_PORT }}
          TG_WEBHOOK_SECRET_TOKEN: ${{ secrets.TG_WEBHOOK_SECRET_TOKEN }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          npm run start:prod:docker
