# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: CI

on:
  pull_request:
    branches: ["*"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22.11.0
      - name: Install dependencies
        run: npm ci
      - name: Build sources
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22.11.0
      - name: Install dependencies
        run: npm ci
      - name: Run unit and integration tests
        run: npm run test:cov
      - name: Run e2e tests
        run: npm run test:e2e:cov
      - name: Run load tests
        run: npm run k6
      - name: Merge unit, integration and e2e test coverage
        run: npm run merge:cov
      - name: Check test coverage badges
        run: npm run make:badges -- --ci --exitCode=1
    timeout-minutes: 15
